### PR TITLE
gtkwave path has changed

### PR DESCRIPTION
**Pull request by kjnsn**

### CODE REVIEW

**Comment by daxtens** [comment]
Looks good. Do the XQuartz instructions need updating?

**Comment by kjnsn** [comment]
Nope. Worked for me.

**Comment by daxtens** [comment]
Cool. Thanks. What version of OS X are you running? I should probably update the most recently tested version (it's currently listed as 10.8, which is now well out of date).

**Comment by kjnsn** [comment]
Tested on 10.10.

**Pull request merged**
